// 1. Data Object (Expand this with more courses)
const advisorData = [
  {
    field: "medicine",
    location: "Perak",
    uni: "IPG",
    logo: "ipg_logo.png",
    code: "UA4440001",
    name: "DIPLOMA SAINS",
    level: "Diploma",
    merit: "87.31%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Perak",
    uni: "IPG",
    logo: "ipg_logo.png",
    code: "UA4481001",
    name: "DIPLOMA SAINS KOMPUTER",
    level: "Diploma",
    merit: "89.22%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Perak",
    uni: "IPG",
    logo: "ipg_logo.png",
    code: "UA4481002",
    name: "DIPLOMA REKA BENTUK DAN PEMBANGUNAN PERMAINAN",
    level: "Diploma",
    merit: "83.87%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Perak",
    uni: "IPG",
    logo: "ipg_logo.png",
    code: "UA4545001",
    name: "DIPLOMA TEKNOLOGI MAKMAL",
    level: "Diploma",
    merit: "83.87%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },

  {
    field: "it",
    location: "Johor",
    uni: "UTHM",
    logo: "uthm_logo.png",
    code: "UB4213001",
    name: "DIPLOMA TEKNOLOGI ANIMASI",
    level: "Diploma",
    merit: "63.82%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "it",
    location: "Johor",
    uni: "UTHM",
    logo: "uthm_logo.png",
    code: "UB4481001",
    name: "DIPLOMA TEKNOLOGI MAKLUMAT",
    level: "Diploma",
    merit: "83.99%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Johor",
    uni: "UTHM",
    logo: "uthm_logo.png",
    code: "UB4521002",
    name: "DIPLOMA KEJURUTERAAN MEKANIKAL",
    level: "Diploma",
    merit: "80.95%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Johor",
    uni: "UTHM",
    logo: "uthm_logo.png",
    code: "UB4522001",
    name: "DIPLOMA KEJURUTERAAN ELEKTRIK",
    level: "Diploma",
    merit: "77.73%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Johor",
    uni: "UTHM",
    logo: "uthm_logo.png",
    code: "UB4524001",
    name: "DIPLOMA TEKNOLOGI KEJURUTERAAN KIMIA",
    level: "Diploma",
    merit: "85.35%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Johor",
    uni: "UTHM",
    logo: "uthm_logo.png",
    code: "UB4526001",
    name: "DIPLOMA KEJUTERAAN AWAM",
    level: "Diploma",
    merit: "78.07%",
    duration: "0 Semester",
    type: "TVET",
  },

  {
    field: "it",
    location: "Melaka",
    uni: "UTEM",
    logo: "utem_logo.png",
    code: "UC4481002",
    name: "DIPLOMA SAINS KOMPUTER",
    level: "Diploma",
    merit: "84.87%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Melaka",
    uni: "UTEM",
    logo: "utem_logo.png",
    code: "UC4521001",
    name: "DIPLOMA KEJURUTERAAN MEKANIKAL",
    level: "Diploma",
    merit: "79.00%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Melaka",
    uni: "UTEM",
    logo: "utem_logo.png",
    code: "UC4522001",
    name: "DIPLOMA KEJURUTERAAN ELEKTRIK",
    level: "Diploma",
    merit: "75.09%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Melaka",
    uni: "UTEM",
    logo: "utem_logo.png",
    code: "UC4523001",
    name: "DIPLOMA KEJURUTERAAN ELEKTRONIK",
    level: "Diploma",
    merit: "74.83%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Melaka",
    uni: "UTEM",
    logo: "utem_logo.png",
    code: "UC4540001",
    name: "DIPLOMA KEJURUTERAAN PEMBUATAN",
    level: "Diploma",
    merit: "66.48%",
    duration: "06 Semester",
    type: "TVET",
  },

  {
    field: "medicine",
    location: "Terengganu",
    uni: "UNISZA",
    logo: "unisza_logo.png",
    code: "UD0010001",
    name: "ASASI PERUBATAN DAN SAINS KESIHATAN",
    level: "Asasi",
    merit: "90.98%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Terengganu",
    uni: "UNISZA",
    logo: "unisza_logo.png",
    code: "UD4481003",
    name: "DIPLOMA SAINS KOMPUTER",
    level: "Diploma",
    merit: "82.60%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Terengganu",
    uni: "UNISZA",
    logo: "unisza_logo.png",
    code: "UD4482001",
    name: "DIPLOMA TEKNOLOGI MAKLUMAT",
    level: "Diploma",
    merit: "79.69%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Terengganu",
    uni: "UNISZA",
    logo: "unisza_logo.png",
    code: "UD4540001",
    name: "DIPLOMA TEKNOLOGI PEMBUATAN",
    level: "Diploma",
    merit: "75.07%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Terengganu",
    uni: "UNISZA",
    logo: "unisza_logo.png",
    code: "UD4723001",
    name: "DIPLOMA SAINS KEJURURAWATAN",
    level: "Diploma",
    merit: "86.57%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Terengganu",
    uni: "UNISZA",
    logo: "unisza_logo.png",
    code: "UD4725002",
    name: "DIPLOMA TEKNOLOGI MAKMAL PERUBATAN",
    level: "Diploma",
    merit: "84.87%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Terengganu",
    uni: "UNISZA",
    logo: "unisza_logo.png",
    code: "UD4726001",
    name: "DIPLOMA FISIOTERAPI",
    level: "Diploma",
    merit: "83.28%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },

  {
    field: "engineering",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE0520001",
    name: "ASASI KEJURUTERAAN",
    level: "Asasi",
    merit: "86.64%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE0545001",
    name: "ASASI SAINS",
    level: "Asasi",
    merit: "88.44%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4213001",
    name: "DIPLOMA ANIMASI",
    level: "Diploma",
    merit: "69.22%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4727001",
    name: "DIPLOMA FARMASI",
    level: "Diploma",
    merit: "87.26%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4726002",
    name: "DIPLOMA FISIOTERAPI",
    level: "Diploma",
    merit: "81.21%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4213004",
    name: "DIPLOMA FOTOMEDIA KREATIF",
    level: "Diploma",
    merit: "0.00%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4723001",
    name: "DIPLOMA KEJURURAWATAN",
    level: "Diploma",
    merit: "84.72%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4526003",
    name: "DIPLOMA KEJURUTERAAN AWAM",
    level: "Diploma",
    merit: "68.13%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4523001",
    name: "DIPLOMA KEJURUTERAAN ELEKTRIK (ELEKTRONIK)",
    level: "Diploma",
    merit: "67.33%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4522002",
    name: "DIPLOMA KEJURUTERAAN ELEKTRIK (KUASA)",
    level: "Diploma",
    merit: "68.38%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4524001",
    name: "DIPLOMA KEJURUTERAAN KIMIA",
    level: "Diploma",
    merit: "75.58%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4521001",
    name: "DIPLOMA KEJURUTERAAN MEKANIKAL",
    level: "Diploma",
    merit: "70.07%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4321001",
    name: "DIPLOMA KOMUNIKASI DAN MEDIA",
    level: "Diploma",
    merit: "64.87%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4421001",
    name: "DIPLOMA MIKROBIOLOGI",
    level: "Diploma",
    merit: "78.00%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4724001",
    name: "DIPLOMA PEMBANTU PEMBEDAHAN PERGIGIAN",
    level: "Diploma",
    merit: "84.38%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4725002",
    name: "DIPLOMA PENGIMEJAN PERUBATAN",
    level: "Diploma",
    merit: "86.57%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4212005",
    name: "DIPLOMA PRODUKSI AUDIO DIGITAL",
    level: "Diploma",
    merit: "60.29%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4545004",
    name: "DIPLOMA SAINS",
    level: "Diploma",
    merit: "72.39%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4481001",
    name: "DIPLOMA SAINS KOMPUTER",
    level: "Diploma",
    merit: "76.71%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4213005",
    name: "DIPLOMA SENI REKA GRAFIK",
    level: "Diploma",
    merit: "0.00%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4462001",
    name: "DIPLOMA STATISTIK",
    level: "Diploma",
    merit: "69.97%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4213003",
    name: "DIPLOMA TEKNOLOGI KOMUNIKASI MEDIA DIGITAL",
    level: "Diploma",
    merit: "67.20%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Selangor",
    uni: "UITM",
    logo: "uitm_logo.png",
    code: "UE4725001E",
    name: "DIPLOMA TEKNOLOGI MAKMAL PERUBATAN",
    level: "Diploma",
    merit: "80.92%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },

  {
    field: "engineering",
    location: "Terengganu",
    uni: "UMT",
    logo: "umt_logo.png",
    code: "UG0010001",
    name: "ASASI STEM",
    level: "Asasi",
    merit: "78.72%",
    duration: "03 Semester",
    type: "Bukan TVET",
  },

  {
    field: "medicine",
    location: "Sabah",
    uni: "UMS",
    logo: "ums_logo.png",
    code: "UH0010001",
    name: "ASASI SAINS",
    level: "Asasi",
    merit: "78.97%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Sabah",
    uni: "UMS",
    logo: "ums_logo.png",
    code: "UH0010002",
    name: "ASASI TEKNOLOGI MAKLUMAT",
    level: "Asasi",
    merit: "83.87%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Sabah",
    uni: "UMS",
    logo: "ums_logo.png",
    code: "UH4520001",
    name: "DIPLOMA KEJURUTERAAN KIMIA (MINYAK DAN GAS)",
    level: "Diploma",
    merit: "87.55%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },

  {
    field: "it",
    location: "Pahang",
    uni: "UMPSA",
    logo: "umpsa_logo.png",
    code: "UJ4481001",
    name: "DIPLOMA SAINS KOMPUTER",
    level: "Diploma",
    merit: "78.50%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Pahang",
    uni: "UMPSA",
    logo: "umpsa_logo.png",
    code: "UJ4521001",
    name: "DIPLOMA KEJURUTERAAN MEKANIKAL",
    level: "Diploma",
    merit: "72.97%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Pahang",
    uni: "UMPSA",
    logo: "umpsa_logo.png",
    code: "UJ4521002",
    name: "DIPLOMA TEKNOLOGI KEJURUTERAAN PEMBUATAN",
    level: "Diploma",
    merit: "63.21%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Pahang",
    uni: "UMPSA",
    logo: "umpsa_logo.png",
    code: "UJ4523001",
    name: "DIPLOMA KEJURUTERAAN ELEKTRIK DAN ELEKTRONIK",
    level: "Diploma",
    merit: "71.42%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Pahang",
    uni: "UMPSA",
    logo: "umpsa_logo.png",
    code: "UJ4524001",
    name: "DIPLOMA KEJURUTERAAN KIMIA",
    level: "Diploma",
    merit: "78.46%",
    duration: "05 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Pahang",
    uni: "UMPSA",
    logo: "umpsa_logo.png",
    code: "UJ4526001",
    name: "DIPLOMA KEJURUTERAAN AWAM",
    level: "Diploma",
    merit: "72.71%",
    duration: "05 Semester",
    type: "TVET",
  },

  {
    field: "medicine",
    location: "Kelantan",
    uni: "UMK",
    logo: "umk_logo.png",
    code: "UL0010001",
    name: "ASASI SAINS",
    level: "Asasi",
    merit: "77.78%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },

  {
    field: "medicine",
    location: "Selangor",
    uni: "UM",
    logo: "um_logo.png",
    code: "UM0421001",
    name: "ASASI SAINS HAYAT",
    level: "Asasi",
    merit: "95.37%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Selangor",
    uni: "UM",
    logo: "um_logo.png",
    code: "UM0440001",
    name: "ASASI SAINS FIZIKAL",
    level: "Asasi",
    merit: "95.06%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },

  {
    field: "it",
    location: "Selangor",
    uni: "UPM",
    logo: "upm_logo.png",
    code: "UP4481001",
    name: "DIPLOMA SAINS KOMPUTER",
    level: "Diploma",
    merit: "80.79%",
    duration: "05 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Selangor",
    uni: "UPM",
    logo: "upm_logo.png",
    code: "UP4524001",
    name: "DIPLOMA KEJURUTERAAN TEKNOLOGI PERTANIAN",
    level: "Diploma",
    merit: "76.89%",
    duration: "06 Semester",
    type: "Bukan TVET",
  },

  {
    field: "medicine",
    location: "Negeri Sembilan",
    uni: "USIM",
    logo: "usim_logo.png",
    code: "UQ0421001",
    name: "ASASI PERUBATAN, PERGIGIAN DAN SAINS",
    level: "Asasi",
    merit: "84.83%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Negeri Sembilan",
    uni: "USIM",
    logo: "usim_logo.png",
    code: "UQ0440005",
    name: "ASASI SAINS FIZIKAL DAN TEKNOLOGI",
    level: "Asasi",
    merit: "76.46%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },

  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4521002",
    name: "DIPLOMA KEJURUTERAAN BAHAN",
    level: "Diploma",
    merit: "62.67%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4521003",
    name: "DIPLOMA TEKNOLOGI KEJURUTERAAN MEKANIKAL",
    level: "Diploma",
    merit: "72.09%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4522001",
    name: "DIPLOMA KEJURUTERAAN ELEKTRIK",
    level: "Diploma",
    merit: "73.02%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4523001",
    name: "DIPLOMA KEJURUTERAAN MEKATRONIK",
    level: "Diploma",
    merit: "71.41%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4523002",
    name: "DIPLOMA KEJURUTERAAN KOMPUTER",
    level: "Diploma",
    merit: "75.87%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4523003",
    name: "DIPLOMA KEJURUTERAAN ELEKTRONIK",
    level: "Diploma",
    merit: "67.95%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4524001",
    name: "DIPLOMA TEKNOLOGI KEJURUTERAAN KIMIA",
    level: "Diploma",
    merit: "0.00%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4540001",
    name: "DIPLOMA KEJURUTERAAN PEMBUATAN",
    level: "Diploma",
    merit: "61.44%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4543001",
    name: "DIPLOMA TEKNOLOGI KEJURUTERAAN POLIMER",
    level: "Diploma",
    merit: "0.00%",
    duration: "06 Semester",
    type: "TVET",
  },
  {
    field: "engineering",
    location: "Perlis",
    uni: "UNIMAP",
    logo: "unimap_logo.png",
    code: "UR4851001",
    name: "DIPLOMA KEJURUTERAAN ALAM SEKITAR",
    level: "Diploma",
    merit: "0.00%",
    duration: "06 Semester",
    type: "TVET",
  },

  {
    field: "engineering",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0000002",
    name: "ASASI SAINS FIZIKAL",
    level: "Asasi",
    merit: "87.33%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0000003",
    name: "ASASI SAINS KESIHATAN BERSEKUTU",
    level: "Asasi",
    merit: "84.85%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0000004",
    name: "ASASI KEJURURAWATAN",
    level: "Asasi",
    merit: "84.01%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0000005",
    name: "ASASI FARMASI",
    level: "Asasi",
    merit: "94.87%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0000012",
    name: "ASASI SAINS HAYAT",
    level: "Asasi",
    merit: "90.42%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0000016",
    name: "ASASI SAINS KEMANUSIAAN",
    level: "Asasi",
    merit: "85.36%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0000017",
    name: "ASASI PERUBATAN",
    level: "Asasi",
    merit: "96.29%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "medicine",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0000018",
    name: "ASASI PERGIGIAN",
    level: "Asasi",
    merit: "96.05%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0481001",
    name: "ASASI SAINS KOMPUTER",
    level: "Asasi",
    merit: "90.19%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Pahang",
    uni: "UIAM",
    logo: "uiam_logo.png",
    code: "UY0520001",
    name: "ASASI KEJURUTERAAN",
    level: "Asasi",
    merit: "85.99%",
    duration: "01 Tahun",
    type: "Bukan TVET",
  },

  {
    field: "medicine",
    location: "Sarawak",
    uni: "UNIMAS",
    logo: "unimas_logo.png",
    code: "UW0010001",
    name: "ASASI SAINS HAYAT",
    level: "Asasi",
    merit: "81.73%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "engineering",
    location: "Sarawak",
    uni: "UNIMAS",
    logo: "unimas_logo.png",
    code: "UW0010002",
    name: "ASASI FIZIKAL",
    level: "Asasi",
    merit: "75.26%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Sarawak",
    uni: "UNIMAS",
    logo: "unimas_logo.png",
    code: "UW0010003",
    name: "ASASI PENGKOMPUTERAN",
    level: "Asasi",
    merit: "83.74%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },

  {
    field: "engineering",
    location: "Kuala Lumpur",
    uni: "UPNM",
    logo: "upnm_logo.png",
    code: "UZ0520001",
    name: "ASASI KEJURUTERAAN DAN TEKNOLOGI",
    level: "Asasi",
    merit: "83.19%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
  {
    field: "it",
    location: "Kuala Lumpur",
    uni: "UPNM",
    logo: "upnm_logo.png",
    code: "UZ0721001",
    name: "ASASI PERUBATAN",
    level: "Asasi",
    merit: "92.15%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },

  {
    field: "engineering",
    location: "Putrajaya",
    uni: "POLITEKNIK",
    logo: "politeknik_logo.png",
    code: "FB0500001",
    name: "ASASI TEKNOLOGI KEJURUTERAAN",
    level: "Asasi",
    merit: "75.14%",
    duration: "02 Semester",
    type: "Bukan TVET",
  },
];

// 2. Select Elements
const fieldSelect = document.querySelectorAll("select")[0];
const locationSelect = document.querySelectorAll("select")[1];
const btnGenerate = document.querySelector(".btn-generate");
const btnReset = document.querySelector(".btn-reset");
const modal = document.getElementById("pathwayModal");
const container = document.getElementById("modalPathways");
const dynamicTitle = document.getElementById("dynamicTitle");
const closeBtn = document.querySelector(".close-btn");

// 3. Main Generate Logic
btnGenerate.addEventListener("click", () => {
  // Get text for the heading
  const selectedFieldText = fieldSelect.options[fieldSelect.selectedIndex].text;
  const selectedLocationText =
    locationSelect.options[locationSelect.selectedIndex].text;

  // Get raw values for filtering the data
  const fieldValue = fieldSelect.value;
  const locationValue = locationSelect.value;

  // Validation: Ensure user picked something
  if (!fieldValue || !locationValue) {
    alert("Please select both a Field and a Location!");
    return;
  }

  // Update the Title at the top of the popup
  if (dynamicTitle) {
    dynamicTitle.innerText = `${selectedFieldText} in ${selectedLocationText}`;
  }

  // Filter Data
  const results = advisorData.filter(
    (item) => item.field === fieldValue && item.location === locationValue,
  );

  // Clear existing content and inject new results
  if (results.length === 0) {
    container.innerHTML = `<p style="text-align:center; padding: 40px; color: #666; width: 100%;">No courses found for this selection yet.</p>`;
  } else {
    container.innerHTML = results
      .map(
        (course) => `
      <div class="course-box">
        <div>
          <div class="course-code">${course.code}</div>
          <div class="course-name">${course.name}</div>
          <div class="course-uni">${course.uni}</div>
        </div>
        <div class="course-details-grid">
          <div class="detail-tag">${course.level}</div>
          <div class="detail-tag">Merit: ${course.merit}</div>
          <div class="detail-tag">${course.duration}</div>
          <div class="detail-tag">${course.type}</div>
        </div>
      </div>
    `,
      )
      .join("");
  }

  // Show the modal and reset its scroll position to the top
  modal.style.display = "block";
  container.scrollTop = 0;
});

// 4. Reset Logic
btnReset.addEventListener("click", () => {
  fieldSelect.selectedIndex = 0;
  locationSelect.selectedIndex = 0;
});

// 5. Modal Close Logic
closeBtn.onclick = () => {
  modal.style.display = "none";
};

// Close when clicking outside the modal box
window.onclick = (event) => {
  if (event.target == modal) {
    modal.style.display = "none";
  }
};
