# Generated by Django 6.0.3 on 2026-04-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='TEMP', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('merit', models.FloatField(default=0)),
                ('duration', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('description', models.TextField(blank=True)),
                ('semester_info', models.CharField(blank=True, max_length=200)),
                ('entry_criteria', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeritResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=50)),
                ('bm', models.CharField(max_length=5)),
                ('bi', models.CharField(max_length=5)),
                ('math', models.CharField(max_length=5)),
                ('sejarah', models.CharField(max_length=5)),
                ('package_subject1', models.CharField(max_length=100)),
                ('package_grade1', models.CharField(max_length=5)),
                ('package_subject2', models.CharField(max_length=100)),
                ('package_grade2', models.CharField(max_length=5)),
                ('best_subject1', models.CharField(max_length=100)),
                ('best_grade1', models.CharField(max_length=5)),
                ('best_subject2', models.CharField(max_length=100)),
                ('best_grade2', models.CharField(max_length=5)),
                ('koko', models.FloatField()),
                ('merit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=5)),
                ('merit_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='main.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.university'),
        ),
    ]
