# Generated by Django 6.0.3 on 2026-05-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeritResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=50)),
                ('bm', models.CharField(max_length=5)),
                ('bi', models.CharField(max_length=5)),
                ('math', models.CharField(max_length=5)),
                ('sejarah', models.CharField(max_length=5)),
                ('package_subject1', models.CharField(max_length=100)),
                ('package_grade1', models.CharField(max_length=5)),
                ('package_subject2', models.CharField(max_length=100)),
                ('package_grade2', models.CharField(max_length=5)),
                ('best_subject1', models.CharField(max_length=100)),
                ('best_grade1', models.CharField(max_length=5)),
                ('best_subject2', models.CharField(max_length=100)),
                ('best_grade2', models.CharField(max_length=5)),
                ('koko', models.FloatField()),
                ('merit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PathwayAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('merit', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('engineering', 'Engineering'), ('business', 'Business'), ('science', 'Science'), ('arts', 'Arts'), ('it', 'IT')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('merit', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('scholarship_type', models.CharField(max_length=255)),
                ('contract', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='main.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjectcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='TEMP', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('merit', models.FloatField(default=0)),
                ('duration', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.university')),
            ],
        ),
    ]
