# Generated by Django 6.0.3 on 2026-04-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='entry_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(default=1, upload_to='logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='semester_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
