# Generated by Django 6.0.3 on 2026-05-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
