# Generated by Django 6.0.3 on 2026-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_institution_description_institution_entry_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
