# Generated by Django 6.0.3 on 2026-05-07 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scholarship_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwayhub',
            options={'verbose_name': 'Pathway Hub Entry', 'verbose_name_plural': 'Pathway Hub Entries'},
        ),
        migrations.AlterModelOptions(
            name='scholarshipcriteria',
            options={'verbose_name_plural': 'Scholarship Criteria'},
        ),
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'verbose_name_plural': 'Subject Categories'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='meritresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_courses', to='main.university'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.subjectcategory'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
