# Generated by Django 6.0.3 on 2026-05-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_institution_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('merit', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('engineering', 'Engineering'), ('business', 'Business'), ('science', 'Science'), ('arts', 'Arts'), ('it', 'IT')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('merit', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='provider',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='contract',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ScholarshipCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjectcategory')),
            ],
        ),
    ]
