# Generated by Django 6.0.3 on 2026-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pathwayhub_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwayhub',
            name='field',
            field=models.CharField(max_length=100),
        ),
    ]
