# Generated by Django 6.0.3 on 2026-04-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=50)),
                ('bm', models.CharField(max_length=5)),
                ('bi', models.CharField(max_length=5)),
                ('math', models.CharField(max_length=5)),
                ('sejarah', models.CharField(max_length=5)),
                ('package_subject1', models.CharField(max_length=100)),
                ('package_grade1', models.CharField(max_length=5)),
                ('package_subject2', models.CharField(max_length=100)),
                ('package_grade2', models.CharField(max_length=5)),
                ('best_subject1', models.CharField(max_length=100)),
                ('best_grade1', models.CharField(max_length=5)),
                ('best_subject2', models.CharField(max_length=100)),
                ('best_grade2', models.CharField(max_length=5)),
                ('koko', models.FloatField()),
                ('merit', models.FloatField()),
            ],
        ),
    ]
