# Generated by Django 6.0.3 on 2026-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pathwayhub_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayadvisor',
            name='field',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='pathwayadvisor',
            name='location',
            field=models.CharField(default='Malaysia', max_length=100),
        ),
        migrations.AddField(
            model_name='pathwayadvisor',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pathwayadvisor',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pathwayadvisor',
            name='course_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayadvisor',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayadvisor',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayadvisor',
            name='merit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pathwayadvisor',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
