# Generated by Django 6.0.3 on 2026-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactinquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'verbose_name_plural': 'Contact Inquiries'},
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_grade1',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_grade2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_subject1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_subject2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='package_grade2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='package_subject2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='course_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='field',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='merit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
