# Generated by Django 6.0.6 on 2026-06-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contactinquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={},
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_grade1',
            field=models.CharField(default='0000', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_grade2',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_subject1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_subject2',
            field=models.CharField(default='0000', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='package_grade2',
            field=models.CharField(default='0000', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='package_subject2',
            field=models.CharField(default='0000', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='course_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='merit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pathwayhub',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Select the date and time when applications close.', null=True),
        ),
    ]
