# Generated by Django 6.0.6 on 2026-06-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contactinquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meritresult',
            name='best_grade1',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_grade2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_subject1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='best_subject2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='package_grade1',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='package_grade2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='package_subject1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meritresult',
            name='package_subject2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
