# Generated by Django 6.0.6 on 2026-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_meritresult_best_grade1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(blank=True, help_text='Select the date when applications close.', null=True),
        ),
    ]
